import { useInstituteContext } from "@/context/InstituteContext";

import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";

import CustomBreadCrumbs from "@/components/CustomBreadCrumbs/CustomBreadCrumbs";

import { cn } from "@/utils";
import PreviewCertificates from "./components/PreviewCertificates";

const ViewCertificates = () => {
  const { institute } = useInstituteContext();
  const breadcrumbItems = {
    previousPages: [
      {
        name: "Home",
        to: "/",
      },
      {
        name: "Dashboard",
        to: "/institute",
      },
    ],
    currentPage: "View Certificates",
  };

  return (
    <div className="flex flex-col h-full gap-y-2 mx-6">
      <CustomBreadCrumbs {...breadcrumbItems} />
      <div className="w-full h-full">
        <Card className={cn("w-full")}>
          <CardHeader className="p-4">
            <CardTitle>Generated Certificate</CardTitle>
            <CardDescription>
              These are the certificates generated by your institutes.
            </CardDescription>
          </CardHeader>
          <CardContent className="pb-4 px-4 ">
            {(institute?.certificateFormats || []).map(
              (certificateFormat, index) => (
                <Card
                  key={index}
                  className={cn(
                    "w-full bg-transparent border-none dark:border-none dark:bg-transparent"
                  )}
                >
                  <CardHeader className="p-0">
                    <CardTitle>
                      {index + 1}. {certificateFormat.name}
                    </CardTitle>
                  </CardHeader>
                  <CardContent className="p-0 pt-2">
                    <PreviewCertificates
                      certificates={certificateFormat.Certificates}
                    />
                  </CardContent>
                </Card>
              )
            )}
          </CardContent>
        </Card>
      </div>
    </div>
  );
};

export default ViewCertificates;
